version: '3'
services:
  localdb:
    image: postgres:11.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    volumes:
      - ./src/main/resources/db/data.sql:/docker-entrypoint-initdb.d/init.sql

